### PR TITLE
Update root.json for 2024

### PR DESCRIPTION
**Pull request by david-christiansen**
This new root.json is signed by all four prior keyholders as well as both of the new ones. Their keys are already in this repository.

### CODE REVIEW

**Comment by david-christiansen** [comment]
I've also created PRs to update the bootstrap sets for both Stack and Cabal:
 * https://github.com/commercialhaskell/pantry/pull/94
 * https://github.com/haskell/cabal/pull/9068

**Comment by gbaz** [comment]
new version deployed, fingers crossed.

**Comment by JonLech** [comment]
@david-christiansen @gbaz Is stack broken until the stack PR linked above is merged?

Getting this key error on 'stack update' with stack 2.11.1:
                                                                                                      
Selected mirror https://hackage.haskell.org/                                                                              
Downloading root                                                                                                          
Could not deserialize <repo>/root.json: Unknown key: b0107b7b3ccbda342459fc9ef98e6ea9bec672a5046bd310ea70915a91d846a7

**Comment by andreabedini** [comment]
See also https://discourse.haskell.org/t/hackage-failure/6953/2

**Pull request merged**
